### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by vitormattos** [matheus-crivellari/talktech-bot#1]
Olá, o arquivo app.php está com o token do seu bot. Isto não é seguro! Se eu baixar seu código e usar seu token, eu consigo me apossar do seu bot até que você revogue o token.

**Comment by matheusan** [comment]
Olá Vitor!

Muito obrigado pelo toque. Essa passou despercebido, vamos corrigir o equivoco.

Grande abraço.
matheusan
